kustomize:
  images:
  - ghcr.io/srikanthsarena/gitops-sre-project/order-service:4f81811d955e1c83522ff90eb607f6234af7bd92
  - ghcr.io/srikanthsarena/gitops-sre-project/user-service:4f81811d955e1c83522ff90eb607f6234af7bd92
