kustomize:
  images:
  - ghcr.io/srikanthsarena/gitops-sre-project/order-service:221f2fbc99b4e208576eb1fc87ed26e216171754
  - ghcr.io/srikanthsarena/gitops-sre-project/user-service:221f2fbc99b4e208576eb1fc87ed26e216171754
