apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-sre-apps
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      order-service=ghcr.io/srikanthsarena/gitops-sre-project/order-service,
      user-service=ghcr.io/srikanthsarena/gitops-sre-project/user-service
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  project: default

  source:
    repoURL: https://github.com/srikanthsarena/gitops-sre-project
    targetRevision: main
    path: gitops/apps
    kustomize: {}   # 👈 THIS IS THE MISSING PIECE

  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-apps

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
