configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=prometheus.yml

generatorOptions:
  disableNameSuffixHash: false


resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
